// ============================================================
// mockData.ts — Static data for frontend-only (mock) mode
// All shapes match the real backend API responses exactly.
// Replace with real API calls by setting USE_MOCK = false in api.ts
// ============================================================

export const mockUser = {
  id: 'mock-user-001',
  name: 'Demo Landlord',
  email: 'demo@homenest.com',
  role: 'landlord' as const,
  avatar: null,
  phone: '(512) 555-0100',
  emailVerified: true,
  createdAt: '2024-01-15T10:00:00Z',
}

export const mockTenant = {
  id: 'mock-user-002',
  name: 'Sarah Johnson',
  email: 'sarah@example.com',
  role: 'tenant' as const,
  avatar: null,
  phone: '(720) 555-0200',
  emailVerified: true,
  createdAt: '2024-02-20T09:00:00Z',
}

export const mockListings = [
  {
    id: 'listing-001',
    title: 'Luxury Downtown Apartment',
    description: 'Beautiful 2BR apartment in the heart of downtown Austin with stunning city views, modern appliances, and premium finishes throughout. Walking distance to restaurants, bars, and the famous 6th Street entertainment district. Building features 24/7 concierge, rooftop pool, and state-of-the-art gym.',
    category: 'apartment',
    rentalType: 'long-term',
    monthlyRent: 2850,
    securityDeposit: 3000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    furnished: true,
    petFriendly: false,
    parkingAvailable: true,
    amenities: ['WiFi', 'Gym', 'Parking', 'Air Conditioning', 'Security', 'Swimming Pool'],
    images: [],
    streetAddress: '123 Congress Ave',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    lat: 30.2672,
    lng: -97.7431,
    contactName: 'Demo Landlord',
    contactPhone: '(512) 555-0100',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'premium',
    featured: true,
    viewCount: 342,
    expiresAt: '2025-03-01T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 12, favorites: 28 },
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },
  {
    id: 'listing-002',
    title: 'Spacious Family Home with Garden',
    description: 'Large 4-bedroom home in a quiet Denver neighborhood with a huge backyard, updated kitchen with granite countertops, hardwood floors throughout, and an excellent school district. Two-car garage, finished basement, and a covered patio perfect for entertaining.',
    category: 'family-home',
    rentalType: 'long-term',
    monthlyRent: 3400,
    securityDeposit: 3500,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    furnished: false,
    petFriendly: true,
    parkingAvailable: true,
    amenities: ['Parking', 'Laundry', 'Air Conditioning'],
    images: [],
    streetAddress: '456 Cherry Creek Dr',
    city: 'Denver',
    state: 'CO',
    zipCode: '80202',
    lat: 39.7392,
    lng: -104.9903,
    contactName: 'Demo Landlord',
    contactPhone: '(720) 555-0201',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'basic',
    featured: false,
    viewCount: 198,
    expiresAt: '2025-01-15T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 6, favorites: 15 },
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'listing-003',
    title: 'Modern Ocean-View Condo',
    description: 'Stunning 3BR condo with direct ocean views from every room. Fully renovated in 2023 with designer finishes, chef\'s kitchen, and a wraparound balcony. Building amenities include a resort-style pool, fitness center, and private beach access.',
    category: 'apartment',
    rentalType: 'long-term',
    monthlyRent: 4200,
    securityDeposit: 4500,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    furnished: true,
    petFriendly: false,
    parkingAvailable: true,
    amenities: ['WiFi', 'Swimming Pool', 'Gym', 'Parking', 'Air Conditioning', 'Security'],
    images: [],
    streetAddress: '789 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    lat: 25.7617,
    lng: -80.1918,
    contactName: 'Demo Landlord',
    contactPhone: '(305) 555-0303',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'premium',
    featured: true,
    viewCount: 512,
    expiresAt: '2025-02-28T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 22, favorites: 41 },
    createdAt: '2024-09-20T10:00:00Z',
    updatedAt: '2024-09-20T10:00:00Z',
  },
  {
    id: 'listing-004',
    title: 'Cozy Student Studio near UT',
    description: 'Perfect for UT Austin students — just a 5-minute walk from campus. This fully furnished studio includes all utilities, high-speed internet, and access to building study rooms. Move-in ready with everything you need.',
    category: 'student',
    rentalType: 'long-term',
    monthlyRent: 950,
    securityDeposit: 950,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 480,
    furnished: true,
    petFriendly: false,
    parkingAvailable: false,
    amenities: ['WiFi', 'Laundry', 'Air Conditioning'],
    images: [],
    streetAddress: '22 Campus Blvd',
    city: 'Austin',
    state: 'TX',
    zipCode: '78712',
    lat: 30.2849,
    lng: -97.7341,
    contactName: 'Demo Landlord',
    contactPhone: '(512) 555-0104',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'basic',
    featured: false,
    viewCount: 276,
    expiresAt: '2025-01-31T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 18, favorites: 32 },
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'listing-005',
    title: 'Rustic Mountain Retreat Cabin',
    description: 'Charming 3BR cabin in the Rockies with breathtaking mountain views, hot tub, wood-burning fireplace, and a wraparound deck. Ski-in/ski-out access in winter. Perfect for families or groups seeking a tranquil mountain escape year round.',
    category: 'vacation',
    rentalType: 'short-term',
    monthlyRent: 2100,
    securityDeposit: 1000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    furnished: true,
    petFriendly: true,
    parkingAvailable: true,
    amenities: ['WiFi', 'Parking', 'Air Conditioning'],
    images: [],
    streetAddress: '1 Mountain View Rd',
    city: 'Aspen',
    state: 'CO',
    zipCode: '81611',
    lat: 39.1911,
    lng: -106.8175,
    contactName: 'Demo Landlord',
    contactPhone: '(970) 555-0105',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'premium',
    featured: true,
    viewCount: 421,
    expiresAt: '2025-03-15T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 14, favorites: 38 },
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'listing-006',
    title: 'Charming Urban Guest House',
    description: 'Private 1BR guest house in the heart of Portland\'s Pearl District. Fully equipped kitchen, private garden patio, and separate entrance. Walking distance to the best restaurants, galleries, and boutiques Portland has to offer.',
    category: 'guest-house',
    rentalType: 'long-term',
    monthlyRent: 1500,
    securityDeposit: 1500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    furnished: true,
    petFriendly: true,
    parkingAvailable: false,
    amenities: ['WiFi', 'Laundry', 'Air Conditioning'],
    images: [],
    streetAddress: '55 Pearl St',
    city: 'Portland',
    state: 'OR',
    zipCode: '97201',
    lat: 45.5231,
    lng: -122.6765,
    contactName: 'Demo Landlord',
    contactPhone: '(503) 555-0106',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'basic',
    featured: false,
    viewCount: 143,
    expiresAt: '2025-01-20T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 7, favorites: 19 },
    createdAt: '2024-11-05T10:00:00Z',
    updatedAt: '2024-11-05T10:00:00Z',
  },
  {
    id: 'listing-007',
    title: 'Bright 1BR Apartment — Midtown',
    description: 'Freshly renovated 1-bedroom in Midtown Manhattan. Floor-to-ceiling windows, stainless steel appliances, in-unit washer/dryer, and a private balcony with skyline views. Steps from the subway, Central Park, and world-class dining.',
    category: 'apartment',
    rentalType: 'long-term',
    monthlyRent: 3200,
    securityDeposit: 6400,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    furnished: false,
    petFriendly: false,
    parkingAvailable: false,
    amenities: ['WiFi', 'Laundry', 'Air Conditioning', 'Security'],
    images: [],
    streetAddress: '400 W 57th St',
    city: 'New York',
    state: 'NY',
    zipCode: '10019',
    lat: 40.7688,
    lng: -73.9900,
    contactName: 'Demo Landlord',
    contactPhone: '(212) 555-0107',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'premium',
    featured: true,
    viewCount: 609,
    expiresAt: '2025-02-10T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 31, favorites: 55 },
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'listing-008',
    title: 'Shared House — 1 Room Available',
    description: 'Furnished room available in a 4-bedroom shared house in Capitol Hill, Seattle. All utilities included. Large common areas, fully equipped kitchen, and a great housemate community. 15-minute walk to Amazon HQ.',
    category: 'shared',
    rentalType: 'long-term',
    monthlyRent: 980,
    securityDeposit: 980,
    bedrooms: 1,
    bathrooms: 2,
    sqft: 220,
    furnished: true,
    petFriendly: false,
    parkingAvailable: false,
    amenities: ['WiFi', 'Laundry'],
    images: [],
    streetAddress: '312 14th Ave E',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98112',
    lat: 47.6231,
    lng: -122.3127,
    contactName: 'Demo Landlord',
    contactPhone: '(206) 555-0108',
    contactEmail: 'demo@homenest.com',
    status: 'active',
    plan: 'basic',
    featured: false,
    viewCount: 88,
    expiresAt: '2025-01-25T00:00:00Z',
    ownerId: 'mock-user-001',
    owner: { id: 'mock-user-001', name: 'Demo Landlord', avatar: null },
    _count: { inquiries: 4, favorites: 9 },
    createdAt: '2024-11-10T10:00:00Z',
    updatedAt: '2024-11-10T10:00:00Z',
  },
]

export const mockInquiries = [
  {
    id: 'inq-001',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '(720) 555-9901',
    message: 'Hi! I\'m very interested in the Austin apartment. I\'m relocating from Denver for work in January. Would it be possible to schedule a virtual tour this week?',
    listingId: 'listing-001',
    listing: { id: 'listing-001', title: 'Luxury Downtown Apartment' },
    read: false,
    createdAt: '2024-12-01T14:30:00Z',
  },
  {
    id: 'inq-002',
    name: 'Marcus Reid',
    email: 'marcus@example.com',
    phone: '(512) 555-9902',
    message: 'Is the apartment still available for a February 1st move-in? We are a couple with no pets and excellent references.',
    listingId: 'listing-001',
    listing: { id: 'listing-001', title: 'Luxury Downtown Apartment' },
    read: true,
    createdAt: '2024-11-28T09:15:00Z',
  },
  {
    id: 'inq-003',
    name: 'Emily Chen',
    email: 'emily@example.com',
    phone: null,
    message: 'I\'m a UT grad student looking for student housing near campus. Does the studio come with utilities included? What\'s the lease length?',
    listingId: 'listing-004',
    listing: { id: 'listing-004', title: 'Cozy Student Studio near UT' },
    read: false,
    createdAt: '2024-12-02T16:45:00Z',
  },
  {
    id: 'inq-004',
    name: 'David Park',
    email: 'david@example.com',
    phone: '(305) 555-9904',
    message: 'Is the Miami condo available for a 6-month lease starting March? We are a family of three, no pets.',
    listingId: 'listing-003',
    listing: { id: 'listing-003', title: 'Modern Ocean-View Condo' },
    read: true,
    createdAt: '2024-11-25T11:00:00Z',
  },
]

export const mockPayments = [
  {
    id: 'pay-001',
    amount: 79,
    currency: 'usd',
    status: 'succeeded',
    stripePaymentId: 'pi_mock_001',
    plan: 'premium',
    listingId: 'listing-001',
    listing: { id: 'listing-001', title: 'Luxury Downtown Apartment' },
    userId: 'mock-user-001',
    createdAt: '2024-11-01T10:05:00Z',
    updatedAt: '2024-11-01T10:05:00Z',
  },
  {
    id: 'pay-002',
    amount: 29,
    currency: 'usd',
    status: 'succeeded',
    stripePaymentId: 'pi_mock_002',
    plan: 'basic',
    listingId: 'listing-002',
    listing: { id: 'listing-002', title: 'Spacious Family Home with Garden' },
    userId: 'mock-user-001',
    createdAt: '2024-10-15T10:05:00Z',
    updatedAt: '2024-10-15T10:05:00Z',
  },
  {
    id: 'pay-003',
    amount: 79,
    currency: 'usd',
    status: 'succeeded',
    stripePaymentId: 'pi_mock_003',
    plan: 'premium',
    listingId: 'listing-003',
    listing: { id: 'listing-003', title: 'Modern Ocean-View Condo' },
    userId: 'mock-user-001',
    createdAt: '2024-09-20T10:05:00Z',
    updatedAt: '2024-09-20T10:05:00Z',
  },
]

export const mockFavorites = [mockListings[0], mockListings[2], mockListings[4]]

export const mockStats = {
  totalListings: 31200,
  cities: 480,
  users: 52000,
  rented: 18500,
}

export const mockDashboardStats = {
  activeListings: 5,
  pendingListings: 1,
  expiredListings: 0,
  totalViews: mockListings.reduce((s, l) => s + l.viewCount, 0),
  totalInquiries: mockListings.reduce((s, l) => s + l._count.inquiries, 0),
  unreadInquiries: mockInquiries.filter(i => !i.read).length,
  totalRevenue: mockPayments.filter(p => p.status === 'succeeded').reduce((s, p) => s + p.amount, 0),
}
